name: Backend CI

on:
  push:
    paths:
      - 'tj-*/**'
  pull_request:
    paths:
      - 'tj-*/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CICD
    strategy:
      matrix:
        service: [tj-user, tj-auth, tj-gateway]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Detect if ${{ matrix.service }} changed
        id: changes
        run: |
          echo "Checking changes in service ${{ matrix.service }}..."
          # 只检测对应服务目录是否有变动
          git fetch origin main
          CHANGED=$(git diff --name-only origin/main HEAD | grep "^${{ matrix.service }}/" || true)
          if [ -z "$CHANGED" ]; then
            echo "no"
          else
            echo "yes"
          fi > changed.txt
          cat changed.txt
          echo "changed=$(cat changed.txt)" >> $GITHUB_OUTPUT

      - name: Build ${{ matrix.service }} if changed
        if: steps.changes.outputs.changed == 'yes'
        run: |
          cd ${{ matrix.service }}
          mvn clean install

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run Maven tests
        run: |
          cd ${{ matrix.service }}
          mvn test
