name: Backend CI

on:
  push:
    paths:
      - 'tj-user/**'
  pull_request:
    paths:
      - 'tj-user/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build tj-user
        run: |
          cd tj-user
          mvn clean install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run Maven tests
        run: |
          cd tj-user
          mvn test
