# .github/workflows/tj-gateway.yml
name: CI for tj-gateway
on:
  push:
    paths:
      - 'tj-gateway/**'
  pull_request:
    paths:
      - 'tj-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build talent-jet
        run:
          mvn clean package -DskipTests

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Unit Testing
        run:
          mvn clean package

      - name: Run Integration Testing
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tj-gateway-jar
          path: tj-gateway/target/*.jar


  snyk:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run:
          npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run:
          snyk auth $SNYK_TOKEN

      - name: Run Snyk to check for vulnerabilities
        run:
          snyk test --severity-threshold=high || true

  release:
    needs: snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download built jar artifact
        uses: actions/download-artifact@v4
        with:
          name: tj-gateway-jar
          path: tj-gateway/target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push Docker Image
        run: |
          docker compose build tj-gateway
          docker compose push tj-gateway